# 利用するdocker-comnposeのバージョン
version: '3.8'

# アプリケーションで動かすための各要素
services:
  memory:
    # 起動するコンテナの設定
    build:
      # ディレクトリの指定
      context: ./memory
    environment:
      - NODE_ENV=development

    # ディレクトリのマウントの設定、:前がホストのディレクトリ、:後がコンテナのディレクトリ
    volumes:
      - ./memory:/usr/src/app
      - /usr/src/app/node_modules

    command: npm start

    # ポート設定、:前がホスト側のポート、:あとがコンテナ側のポート
    ports:
      - "3000:3000"

    tty: true
